### ISSUE TITLE
Section to create a new "My Project Scratch Org" does not allow Scratch Org creation in some circumstances

### ISSUE THREAD

**Issue by coriobriensfdo** [SFDO-Tooling/Metecho#1087]
**Issue:**

When on the main Metecho page for a project, attempting to create a new scratch org within the "My Project Scratch Org" section is not initially possible if someone else is already creating a scratch org using that option. Button is removed and replaced with the "Creating Org..." notification.

![Screen Shot 2021-07-15 at 9 40 56 AM](https://user-images.githubusercontent.com/37851761/125832920-79cb64d0-2575-4df6-bc71-4ec74a6e7370.png)

**Steps to repro:**

1. Log into Metecho ensuring you have write access to at least one project, and navigate to that project page. For example https://metecho.herokuapp.com/projects/summit-events-app.
2. Ask another use to also log in and navigate to that same project page.
3. Ask the other person to click the Create Scratch Org button within the My Project Scratch Org section to kick off creating a scratch org for the project. 
![Screen Shot 2021-07-15 at 10 38 49 AM](https://user-images.githubusercontent.com/37851761/125833187-ffb7c861-122a-43e8-8c41-34b182b3f51e.png)

4. Note that on your screen the creation option is replaced with a message that the scratch org is being created, preventing you from creating your own scratch org.
![Screen Shot 2021-07-15 at 9 40 56 AM](https://user-images.githubusercontent.com/37851761/125833352-bec8f30a-da54-4875-b4ff-683088b0458c.png)

5. Refresh your browser, and you should see the create button again. This will remain on your screen for a short time before being replaced with the creation message again (even if you don't click the button to create a new scratch org).

**Workaround:**

Refresh your browser, then quickly click the Create Scratch Org button.

**Comment by jgerigmeyer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Project scratch org creation is prevented if another user is creating one.](https://trello.com/c/VtUxIJlx/309-project-scratch-org-creation-is-prevented-if-another-user-is-creating-one)
