### ISSUE TITLE
Can I use metecho for my own projects?

### ISSUE THREAD

**Issue by rsoesemann** [SFDO-Tooling/Metecho#1587]
Love this tool. I connected it to my Github https://github.com/rsoesemann?tab=projects which has a public project but I can't see anything in Metecho.

![Screenshot 2021-12-08 at 13 50 34](https://user-images.githubusercontent.com/8180281/145211247-7d7d2501-b80b-46bc-b473-0f3d964d7e83.png)

What am I doing wrong?

**Comment by davisagli** [comment]
The instance of Metecho run by Salesforce.org Release Engineering at metecho.herokuapp.com is only available for projects participating in a Salesforce.org Community Sprint or the Salesforce.org Open Source Commons.
