### ISSUE TITLE
HELP : button SVG files are not loading on Heroku

### ISSUE THREAD

**Issue by RupertBarrow** [SFDO-Tooling/Metecho#1591]
Is there a Django setting or something to make button SVG icons not get rejected by a CORS constraint ?

Here is the error message on loading any Metecho page which displays a button/menu : 
`Unsafe attempt to load URL data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' display='none'%3e%3csymbol viewBox='0 0 52 52' id='activity' xmlns='http://www.w3.org/2000/svg'%3e%3cpath d='M37.618 11.67c-1.54.5-2.783.98-3.723 1.438-.747.364-1.687.901-2.814 1.61.086 1.882.084 3.463-.009 4.754-.094 1.304-.342 3.173-.746 5.63l-.001.003c2.815 2.028 4.848 3.56 6.11 4.604.163.135.633.584.856.783l4.344-1.82.028-.074c.627-1.347 1.145-3.186 1.54-5.507.322-1.899.376-3.99.159-6.276l-5.744-5.14...-14-14S14.3 8 22 8s14 6.3 14 14-6.3 14-14 14z'/%3e%3c/symbol%3e%3csymbol viewBox='0 0 52 52' id='zoomout' xmlns='http://www.w3.org/2000/svg'%3e%3cpath d='M19 25h12c.6 0 1-.4 1-1v-4c0-.6-.4-1-1-1H19M19 19h-6c-.6 0-1 .4-1 1v4c0 .6.4 1 1 1h6'/%3e%3cpath d='M49.6 45.3L38.1 33.8C40.5 30.5 42 26.4 42 22c0-11-9-20-20-20S2 11 2 22s9 20 20 20c4.4 0 8.5-1.5 11.8-3.9l11.5 11.5c.6.6 1.5.6 2.1 0l2.1-2.1c.6-.6.6-1.6.1-2.2zM22 36c-7.7 0-14-6.3-14-14S14.3 8 22 8s14 6.3 14 14-6.3 14-14 14z'/%3e%3c/symbol%3e%3c/svg%3e#down from origin https://mymetecho.herokuapp.com. Domains, protocols and ports must match`

**Comment by davisagli** [comment]
Are you seeing this in Safari? If so I believe we already have a fix in progress.

**Comment by RupertBarrow** [comment]
Yes
