### ISSUE TITLE
HELP : how can I do Dev Hub pooling in Metecho

### ISSUE THREAD

**Issue by RupertBarrow** [SFDO-Tooling/Metecho#1592]
Salesforce Dev Hubs limits at 6 the number of scratch orgs created per day.
Can I implement Dev Hub pooling in Metecho to work around this limit ?

**Comment by davisagli** [comment]
Metecho does not have a pooling feature. But if you do not configure a global DEVHUB_USERNAME, then each Metecho user can connect their own dev hub. Also, Dev Hubs associated with a production org usually have higher limits than Dev Hubs associated with a Developer Edition org, which it sounds like is what you are using.
